Repository cybertec-postgresql/pgwatch2, pull requests merged in 2022-12, with the labels that each got.

#547 [-] fix `table_bloat_approx_summary_sql` when `tblpages = 0`, closes #491
  pgwatch2/metrics/table_bloat_approx_summary_sql/12/metric_su.sql
  pgwatch2/metrics/table_bloat_approx_summary_sql/9.0/metric_su.sql
Labels: bug, metrics

#551 [-] fix executing queries on standby databases with pooling, fixes #520
  pgwatch2/pgwatch2.go
Labels: bug, gatherer-daemon

#521 [+] add new stat activity grid report
  grafana_dashboards/postgres/v8/stat-activity/dashboard.json
  grafana_dashboards/postgres/v8/stat-activity/title.txt
  pgwatch2/metrics/preset-configs.yaml
  pgwatch2/metrics/stat_activity/10/metric.sql
  pgwatch2/metrics/stat_activity/10/metric_su.sql
  pgwatch2/metrics/stat_statements/13/metric.sql
  pgwatch2/metrics/stat_statements/13/metric_su.sql
  pgwatch2/metrics/stat_statements/15/metric.sql
  pgwatch2/metrics/stat_statements/15/metric_su.sql
  pgwatch2/metrics/stat_statements/9.2/metric.sql
  pgwatch2/metrics/stat_statements/9.2/metric_su.sql
  pgwatch2/metrics/stat_statements/9.4/metric.sql
  pgwatch2/metrics/stat_statements/9.4/metric_su.sql
  pgwatch2/metrics/table_io_stats/10/metric.sql
  pgwatch2/metrics/table_stats/10/metric.sql
  pgwatch2/metrics/table_stats_approx/10/metric.sql
  pgwatch2/sql/config_store/config_store.sql
  pgwatch2/sql/config_store/metric_definitions.sql
Labels: metrics, dashboards

#558 [*] deprecate Influx docker images in Release GHA workflow, closes #544
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: docker, influx, packaging

#570 [!] bump Go packages versions
  pgwatch2/go.mod
  pgwatch2/go.sum
Labels: gatherer-daemon, dependencies, go

#573 [+] make unique dbname maintenance less costly for multi-daemon setups, fixes #525
  pgwatch2/pgwatch2.go
Labels: enhancement, gatherer-daemon, performance
