Repository cybertec-postgresql/pgwatch2, pull requests merged in 2024-02, with the labels that each got.

#739 [-] fix warning about `yaml.load()` is deprecated, closes #738
  pgwatch2/metrics/00_helpers/rollout_helper.py
Labels: enhancement

#742 [-] change `StatActivity` dashboard identifier value to `null`, closes #741
  grafana_dashboards/postgres/v8/stat-activity/dashboard.json
Labels: dashboards

#744 [-] fix typo in documentation
  docs/advanced_features.rst
Labels: documentation
