Repository cybertec-postgresql/pgwatch2, pull requests merged in 2024-03, with the labels that each got.

#754 [+] allow setting arbitrary configs to the webui pod
  helm-chart/templates/deployment.yaml
  webpy/templates/stats-summary.html
Labels: enhancement

#757 [-] fix `readthedocs` deployment
  .readthedocs.yaml
  docs/requirements.txt
Labels: documentation, deployment

#758 [*] move ansible playbooks to `cybertec-postgresql/pgwatch2-charts`
  ansible/perftest/config-db-test-hosts-multiplied.sql
  ansible/perftest/hosts
  ansible/perftest/install-postgres-and-prepare-for-monitoring.yml
Labels: external
